# Generated by Django 4.2.5 on 2023-11-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
