# Generated by Django 4.2.5 on 2023-10-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='caratula',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='modificacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='stock',
        ),
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100, verbose_name='Apellido del Autor/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='nacimiento',
            field=models.IntegerField(default=0, verbose_name='Año de nacimiento del Autor/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='pais',
            field=models.CharField(default='Pais', max_length=100, verbose_name='Nacionalidad del Autor/a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Autor/a'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.IntegerField(verbose_name='fecha de publicación'),
        ),
    ]
