# Generated by Django 4.2.5 on 2023-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='default_book_cover.png', upload_to='media/'),
        ),
    ]
