# Generated by Django 4.2.5 on 2023-10-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_autor_apellido_alter_autor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=50, verbose_name='contraseña'),
        ),
    ]
